name: Report an issue with Valetudo Vacuum Camera
description: Report an issue with Valetudo Vacuum Camera.
labels: bug
assignees: 'SCA075'
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a question, feature or enhancement request, please use the dedicated form.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have updated the integration to the latest version available
          required: true
        - label: I have checked if the problem is already reported
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: bug-version
    validations:
      required: true
    attributes:
      label: What version of an integration has described problem?
      placeholder: vX.X.X
  - type: input
    id: last-working-version
    validations:
      required: false
    attributes:
      label: What was the last working version of an integration?
      placeholder: vX.X.X
      description: >
        If known, otherwise leave blank.
  - type: input
    id: vacuum-model
    validations:
      required: true
    attributes:
      label: What vacuum model do you have problems with?
      placeholder: Roborock.V1
  - type: input
    id: valetudo-firmware-version
    validations:
      required: true
    attributes:
      label: Please firmware installed on your Vacuum.
      placeholder: yyyy.mm.x
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of platform you use?
      description: >
        As per there are limitations recently reported, please specify the machine were Home Assistant Runs.

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Intel NUC (or generic x86_64)
        - ARM (Raspberry Pi, Odroid, etc.) < 4GB
        - ARM (Raspberry Pi, Odroid, etc.) > 4GB
        - VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.
  - type: input
    id: ha-version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant do you use?
      placeholder: core-
      description: >
        Can be found in: [Configuration panel -> Info](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Configuration panel -> Info](https://my.home-assistant.io/redirect/info/).

        [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    validations:
      required: false
    attributes:
      label: Camera's settings.
      description: |
        Please provide the used options and settings (if problems with colours just value and used filed).
      render: yaml
  - type: textarea
    attributes:
      label: Logs or Errors shown in the HA snapshots (please enable the Debug Mode)
      render: shell
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information, use the field below.
